# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://aryannath.github.io/'
baseurl: ''
title: 'Aryan Nath'
description: 'Know more about me :-'
permalink: pretty
logo: "/assets/img/site-logo.jpeg"
avatarurl: "/assets/img/site-logo.jpeg"
repo: "https://github.com/Aryannath/aryannath.github.io"

sass:
  style: compressed
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike  
  
encoding: utf-8 # Make sure the encoding is right

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"
  
twitter:
  username: aryannath25

author: Aryan Nath

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/DavidDarnes
  LinkedIn: https://www.linkedin.com/in/daviddarnes
  GitHub: https://github.com/daviddarnes
  link: https://darn.es
  RSS: /feed.xml
    
email: "aryannath2@gmail.com"

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

google_analytics: 'googlef563022ea5552afd'

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
