# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://aryannath.github.io/'
baseurl: ''
title: 'Aryan Nath'
description: 'Know more about me :-'
permalink: pretty
logo: "/assets/img/site-logo.jpeg"
avatarurl: "/assets/img/site-logo.jpeg"
repo: "https://github.com/Aryannath/aryannath.github.io"


# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"
  
twitter:
  username: aryannath25

author: Aryan Nath

contact:
  github:     https://github.com/Aryannath
  linkedin:   https://www.linkedin.com/in/aryan-nath-7324aa200/
  twitter:    https://twitter.com/aryannath25
  instagram:  https://www.instagram.com/aryan_nath25/
  kaggle:     https://www.kaggle.com/aryannath
    
mail: aryannath2@gmail.com

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
