

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-commonmark
- jekyll-include-cache
- jekyll-feed
- jemoji
- github-pages


# Site settings
encoding: utf-8
url: 'https://aryannath.github.io/'
baseurl: ''
title: "Aryan Nath"
description: 'Know more about me :-'
permalink: pretty
logo: "/assets/img/site-logo.jpeg"
avatarurl: "/assets/img/site-logo.jpeg"
repo: "https://github.com/Aryannath/aryannath.github.io"

sass:
  style: compressed
  sass_dir: _sass
  
# default markdown processor and highlighter
markdown: kramdown
highlighter: rouge
error_mode: strict

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"
  
twitter:
  username: aryannath25

author: Aryan Nath
email: "aryannath2@gmail.com"

google_analytics: 'googlef563022ea5552afd'


sass:
  style: compressed # Style compression
permalink: /:categories/:title/  # define url construction
timezone: America/Los_Angeles # Timezone for blog posts and alike

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
    
    
social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  github: https://github.com/Aryannath
  linkedIn: https://www.linkedin.com/in/aryan-nath-7324aa200/
  twitter: https://twitter.com/aryannath25
  instagram: https://www.instagram.com/aryan_nath25/
  kaggle: https://www.kaggle.com/aryannath
  RSS: /feed.xml
  
sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true  
